### ISSUE TITLE
full paths to {ca,ld}65 didn't work

### ISSUE THREAD

**Issue by jeffythedragonslayer** [bbbradsmith/NES-ca65-example#4]
I had truncate the calls to ca65 and ld65 down to the basenames to get compile_example.bat to run.

**Comment by bbbradsmith** [comment]
Yes, if you want to run ca65.exe from a different location than explained in example.txt, you will have to customize the paths.

**Comment by jeffythedragonslayer** [comment]
Ah, example.txt didn't look too important 😅
