### ISSUE TITLE
.fdb file missing?

### ISSUE THREAD

**Issue by DoctorMikeReddy** [bbbradsmith/NES-ca65-example#7]
Running this on an Apple Silicon macbook, I get this error:
"Warning: Failed to open file '/Users/mreddy01/Downloads/NES-ca65-example-unix/example.fdb' for reading"
Is this an issue?

**Comment by bbbradsmith** [comment]
You'd have to provide more information. I don't see any reference to any "fdb" file in the makefile or shell scripts. What exactly did you run to get this error?

**Comment by DoctorMikeReddy** [comment]
Running make test:

ld65 -o example.nes -C example.cfg example.o -m example.map.txt -Ln example.labels.txt --dbgfile example.nes.dbg
fceux example.nes
timeStampModuleInit
Starting FCEUX 2.6.6...
NTSC mode set
NTSC mode set
Loading /Users/mreddy01/Downloads/NES-ca65-example-unix/example.nes...

 PRG ROM: 2 x 16KiB = 32 KiB
 CHR ROM: 1 x  8KiB = 8 KiB
 ROM CRC32: 0xd7a25ace
 ROM MD5:  0xd26a1c4258a1eb94aaa69651e792c838
 Mapper #: 0
 Mapper name: NROM
 Mirroring: Vertical
 Battery-backed: No
 Trained: No

Power on
No Debug Windows Open: Skipping loading of breakpoint data
Warning: Failed to open file '/Users/mreddy01/Downloads/NES-ca65-example-unix/example.fdb' for reading
Initializing video... Video Mode: 256 x 224 x 32 bpp 
Loading SDL sound with coreaudio driver...
NTSC mode set
NTSC mode set
Running on Platform: cocoa
GL Ratio: 2.000000 
Emulator Start
GL Version: 2.1 Metal - 83.1 
Emulator Exit
mreddy01@Little-Vic NES-ca65-example-unix %

**Comment by bbbradsmith** [comment]
Okay, this appears to be a warning from FCEUX and not anything to do with this project or makefile. Please raise the issue of the warning with the FCEUX project if you feel it needs to be addressed.

**Comment by DoctorMikeReddy** [comment]
Ok, thanks

**Comment by DoctorMikeReddy** [comment]
Ahah, FCEUX has changed its debugger file extension from .dbg to .fdb to avoid conflicts. Details here: https://forums.nesdev.org/viewtopic.php?t=24316

And this from the Changelog:
"Debugger
Changed debugger data save file extension to be .fdb instead of .dbg so that it does not conflict/overwrite ld65 debug symbol files"
https://fceux.com/web/help/WhatsNew265.html

**Comment by bbbradsmith** [comment]
Right, but I don't see any reason there should be a warning given when such a file doesn't exist? That file is to keep track of a user's debugging session. It should only exist if that user has debugged that particular ROM with FCEUX before.

**Comment by DoctorMikeReddy** [comment]
I agree. I'll pass it on to the FCEUX team
