### ISSUE TITLE
ld65: Error: Cannot generate most of the files due to memory area overflows

### ISSUE THREAD

**Issue by rotolonico** [bbbradsmith/NES-ca65-example#8]
Hello,
thanks for the NES example, it looks very useful but I am having some trouble building it (I am likely doing something wrong on my end).

I am using the example.cfg and building using cc65 and more specifically, in a VSCode build task with the following configs:
[cl65config.json](https://github.com/bbbradsmith/NES-ca65-example/files/14899331/cl65config.json)
[tasks.json](https://github.com/bbbradsmith/NES-ca65-example/files/14899334/tasks.json)

Upon building though, I get the following overflows:
![image](https://github.com/bbbradsmith/NES-ca65-example/assets/8409175/84a0da3c-7d43-485f-b165-df72c99d9168)
OAM overflow is especially weird because I can see that in the code in the OAM segment exactly 256 bytes are reserved and the cfg defines 256 bytes, but it is still giving me a 256 bytes overflow

**Comment by bbbradsmith** [comment]
You didn't share the actual ld65 command you used, only the errors produced, so it is hard to guess what's going wrong. Maybe you've linked the objects twice, causing the data in each of those segments to double?

I don't know anything about how your VSCode json files work, sorry. Maybe you can take a look at what ld65 command line they have produced, and compare it to the working one I gave in the example batch file: [compile_example.bat](https://github.com/bbbradsmith/NES-ca65-example/blob/master/compile_example.bat)

**Comment by rotolonico** [comment]
Hey thanks for the quick reply, I think I understood my problem. I think my ld65 command was set up with a wrapper in mind so it linked the working file + the wrapper, but in this case the two files were identical, so as you said, it did end up linking the same file twice.

I made my own custom VSCode task that runs your .sh script in the UNIX version of this repo and it works!
